
# pipeline tracking code

stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage01_data_ingestion.py
    deps: 
      - src/cnnClassifier/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage02_prepare_base_model.py
    deps: 
      - src/cnnClassifier/pipeline/stage02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model/base_model_updated.h5

  model_training:
    cmd: python src/cnnClassifier/pipeline/stage03_model_training.py
    deps: 
      - src/cnnClassifier/pipeline/stage03_model_training.py
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_base_model
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/model_training/model.h5

  model_evaluation:
    cmd: python src/cnnClassifier/pipeline/stage04_model_evaluation.py
    deps: 
      - src/cnnClassifier/pipeline/stage04_model_evaluation.py
      - artifacts/data_ingestion/Chest-CT-Scan-data      
      - artifacts/model_training/model.h5
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false 
    

