# vgg16 model parameters

AUGMENTATION: True
IMAGE_SIZE: [224,224,3]
BATCH_SIZE: 16
INCLUDE_TOP: False # drop dense layer
EPOCHS: 2
CLASSES: 2 #o/p 2 classes
WEIGHTS: imagenet # fixed weights
LEARNING_RATE: 0.01